### ISSUE TITLE
Cannot insert join.pfx certificate while building FS2020 version

### ISSUE THREAD

**Issue by matt-post** [omx5o/JoinFS#2]
Hi, I am trying to build for FS2020 version, but keep running into the same error (see title). Any help greatly appreciated and much thanks in advance.

**Comment by omx5o** [comment]
Hi. You can create a new certificate from the Visual Studio project
settings. If you find the under security I think, you should be able to
create a new one. If it asks for a password, have a look at the project
file in raw text format and at the bottom you should see a line that builds
the certificate. I think the password specified there needs to match the
one used to create the pfx file.

**Comment by matt-post** [comment]
Thank you very very much!
